// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ldsc_bootstrap_cpp
List ldsc_bootstrap_cpp(NumericMatrix Zmat, NumericMatrix Nmat, NumericVector LDSC, IntegerVector Block, NumericMatrix GCovInit, NumericMatrix ECovInit, int sampling_time, double z_thresh, double cov_thresh, int M, int n_threads);
RcppExport SEXP _ldscR_ldsc_bootstrap_cpp(SEXP ZmatSEXP, SEXP NmatSEXP, SEXP LDSCSEXP, SEXP BlockSEXP, SEXP GCovInitSEXP, SEXP ECovInitSEXP, SEXP sampling_timeSEXP, SEXP z_threshSEXP, SEXP cov_threshSEXP, SEXP MSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Zmat(ZmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Nmat(NmatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LDSC(LDSCSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Block(BlockSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type GCovInit(GCovInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ECovInit(ECovInitSEXP);
    Rcpp::traits::input_parameter< int >::type sampling_time(sampling_timeSEXP);
    Rcpp::traits::input_parameter< double >::type z_thresh(z_threshSEXP);
    Rcpp::traits::input_parameter< double >::type cov_thresh(cov_threshSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ldsc_bootstrap_cpp(Zmat, Nmat, LDSC, Block, GCovInit, ECovInit, sampling_time, z_thresh, cov_thresh, M, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ldscR_ldsc_bootstrap_cpp", (DL_FUNC) &_ldscR_ldsc_bootstrap_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_ldscR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
