# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldsc_bootstrap_cpp <- function(Zmat, Nmat, LDSC, Block, GCovInit, ECovInit, sampling_time, z_thresh, cov_thresh, M, n_threads = -1L) {
    .Call(`_ldscR_ldsc_bootstrap_cpp`, Zmat, Nmat, LDSC, Block, GCovInit, ECovInit, sampling_time, z_thresh, cov_thresh, M, n_threads)
}

